version: '3.8'

services:
  rent-event:
    build: .
    image: rentevent:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    command: ["java", "-jar", "/app/app.jar"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yopues"]
      interval: 30s
      timeout: 20s
      retries: 10

volumes:
  postgres_data:
