package com.rentevent.model.enums.provincias;

public enum EcuadorProvincias {
    AZUAY, BOLÍVAR, CAÑAR, CARCHI, CHIMBORAZO, COTOPAXI,
    EL_ORO, ESMERALDAS, GALÁPAGOS, GUAYAS, IMBABURA, LOJA,
    LOS_RÍOS, MANABÍ, MORONA_SANTIAGO, NAPO, ORELLANA,
    PASTAZA, PICHINCHA, SANTA_ELENA, SANTO_DOMINGO_DE_LOS_TSÁCHILAS,
    SUCUMBÍOS, TUNGURAHUA, ZAMORA_CHINCHIPE;

}